/**
 * Seed: Strip all guides to skeleton headings only (h2/h3).
 *
 * Usage:
 *   SANITY_API_TOKEN=<write-token> npx tsx scripts/seed-guides-skeleton.ts
 */

import { createClient } from "@sanity/client";

const token = process.env.SANITY_TOKEN || process.env.SANITY_API_TOKEN;
if (!token) { console.error("Set SANITY_API_TOKEN"); process.exit(1); }

const client = createClient({
  projectId: "u2kuytve",
  dataset: "production",
  apiVersion: "2025-01-01",
  token,
  useCdn: false,
});

let _k = 0;
const key = () => `k${++_k}`;
const span = (text: string) => ({ _type: "span" as const, _key: key(), text, marks: [] });
const h2 = (t: string) => ({ _type: "block" as const, _key: key(), style: "h2", markDefs: [], children: [span(t)] });
const h3 = (t: string) => ({ _type: "block" as const, _key: key(), style: "h3", markDefs: [], children: [span(t)] });

const guides: { id: string; title: string; body: ReturnType<typeof h2>[] }[] = [
  {
    id: "22a65a86-a69e-47f8-8e54-83e5ad670090",
    title: "Avatar Creation",
    body: [
      h2("Before You Begin"),
      h2("Choosing Your Name"),
      h3("Name Format"),
      h3("Name Rules"),
      h2("Appearance Customisation"),
      h3("Gender"),
      h3("Face and Body"),
      h3("What Can Be Changed Later"),
      h3("What Cannot Be Changed"),
      h2("Starting Planet"),
      h3("Planet Calypso"),
      h3("Planet Arkadia"),
      h3("Planet Cyrene"),
      h3("Next Island"),
      h3("Planet Toulan"),
      h2("The Tutorial"),
      h3("What the Tutorial Covers"),
      h3("Should You Skip It?"),
      h2("After Character Creation"),
      h3("Verify Your Account"),
      h3("First Deposit"),
      h3("Join a Society"),
    ],
  },
  {
    id: "f3479b19-6983-4191-85e4-a17a201cec50",
    title: "Getting to The Howling Mine",
    body: [
      h2("What Is The Howling Mine?"),
      h2("Where Is It Located?"),
      h3("Coordinates"),
      h2("Getting There from a Starting Area"),
      h3("Option 1: Teleporter"),
      h3("Option 2: Running on Foot"),
      h3("Option 3: Vehicle"),
      h3("Option 4: Summon from a Society Member"),
      h2("If You Are on Another Planet"),
      h3("Space Travel"),
      h3("Hitchhiking"),
      h3("Quad Wing"),
      h2("What to Bring"),
      h3("Essential Gear"),
      h3("Optional"),
      h2("Once You Arrive"),
      h3("Register the Teleporter"),
      h3("Introduce Yourself"),
      h3("Explore the Area"),
    ],
  },
  {
    id: "5cf10259-9304-433d-b53d-5fef9849bcc0",
    title: "Setesh Guide",
    body: [
      h2("What Is Setesh?"),
      h2("The Setesh Mission Chain"),
      h3("Starting the Missions"),
      h3("Mission Sequence Overview"),
      h2("Starter Equipment Rewards"),
      h3("What You Receive"),
      h3("Keep or Sell?"),
      h2("Combat in Setesh"),
      h3("Your First Fight"),
      h3("Key Controls"),
      h2("Leaving Setesh"),
      h3("When to Leave"),
      h3("How to Leave"),
      h3("What Happens Next"),
      h2("Common Setesh Questions"),
      h3("Can I Go Back to Setesh?"),
      h3("I Skipped a Mission — Can I Redo It?"),
      h3("Is Setesh the Same on Every Planet?"),
    ],
  },
  {
    id: "2b9acd87-4a7c-44c6-bb5d-dba501fdacfe",
    title: "Mining 101",
    body: [
      h2("What Is Mining?"),
      h2("Essential Equipment"),
      h3("The Finder"),
      h3("The Excavator"),
      h3("Probes"),
      h2("How Mining Works"),
      h3("Drop a Probe"),
      h3("Read the Result"),
      h3("Extract the Claim"),
      h3("Two Resource Types"),
      h2("Mining Costs"),
      h3("Cost Per Probe Drop"),
      h3("Typical Beginner Budget"),
      h2("Where to Mine"),
      h3("Choosing a Location"),
      h3("Mining Patterns"),
      h2("Understanding Claims"),
      h3("Claim Size"),
      h3("Globals and Hall of Fame"),
      h2("Skills and Progression"),
      h3("Key Mining Skills"),
      h3("How Skills Build"),
      h2("Tips for New Miners"),
    ],
  },
  {
    id: "8849158f-a819-47f2-aec1-ee36cd33c135",
    title: "Getting Started (Asteroid Mining)",
    body: [
      h2("What Is Asteroid Mining?"),
      h2("Prerequisites"),
      h3("Skills"),
      h3("Equipment"),
      h3("Budget"),
      h2("Getting to an Asteroid"),
      h3("The Space System"),
      h3("Finding Asteroids"),
      h3("Transport Options"),
      h2("Mining on an Asteroid"),
      h3("How It Differs from Planetary Mining"),
      h3("The Mining Loop"),
      h2("PvP and Safety"),
      h3("Lootable vs Non-Lootable Space"),
      h3("Staying Safe"),
      h2("Asteroid Resources"),
      h3("Common Asteroid Ores"),
      h3("Markup Potential"),
      h2("Joining the Community"),
      h3("The Howling Mine"),
      h3("Group Mining Runs"),
    ],
  },
  {
    id: "aee8c61c-9362-4b32-9c2c-fe9aed728e38",
    title: "Crafting 101",
    body: [
      h2("What Is Crafting?"),
      h2("How Crafting Works"),
      h3("The Crafting Interface"),
      h3("The Craft Attempt"),
      h3("Outcomes"),
      h2("Blueprints"),
      h3("What Are Blueprints?"),
      h3("Blueprint Sources"),
      h3("Blueprint Quality Rating (QR)"),
      h2("Materials"),
      h3("Material Types"),
      h3("Buying Materials"),
      h2("Crafting Categories"),
      h3("Weapons"),
      h3("Armor"),
      h3("Tools"),
      h3("Ammunition"),
      h3("Components"),
      h2("Crafting Economics"),
      h3("Cost Per Attempt"),
      h3("Markup and Profit"),
      h3("The Residue Problem"),
      h2("Getting Started as a Crafter"),
      h3("First Steps"),
      h3("Beginner Tips"),
    ],
  },
  {
    id: "b58ea730-a8c2-4ed1-8e92-db259b73c1f9",
    title: "Asteroid Mining 101",
    body: [
      h2("Asteroid Mining Overview"),
      h2("Types of Asteroids"),
      h3("Public Asteroids"),
      h3("Taxed Asteroids"),
      h3("Private Asteroids"),
      h2("Space-Exclusive Resources"),
      h3("Why Asteroid Ores Are Valuable"),
      h3("Notable Space Resources"),
      h2("Equipment for Asteroid Mining"),
      h3("Finder Selection"),
      h3("Amplifiers"),
      h3("Transport"),
      h2("Mining Strategy on Asteroids"),
      h3("Systematic Coverage"),
      h3("Timing and Competition"),
      h3("Claim Management"),
      h2("Dealing with Pirates"),
      h3("The PvP Reality"),
      h3("Risk Mitigation"),
      h3("What Happens If You Die"),
      h2("Economics of Asteroid Mining"),
      h3("Cost Breakdown"),
      h3("Revenue"),
      h3("Profitability"),
      h2("Next Steps"),
    ],
  },
  {
    id: "guide-hunting-101",
    title: "Hunting 101",
    body: [
      h2("What Is Hunting?"),
      h2("Essential Equipment"),
      h3("Weapon"),
      h3("Ammunition"),
      h3("Healing Tool (FAP)"),
      h3("Armor"),
      h2("Weapon Types"),
      h3("Ranged Weapons"),
      h3("Melee Weapons"),
      h3("Mindforce"),
      h2("Understanding Damage Types"),
      h3("The Nine Damage Types"),
      h2("Mob Maturity Levels"),
      h2("Your First Hunt"),
      h3("Step 1: Gear Up"),
      h3("Step 2: Pick Your Target"),
      h3("Step 3: Engage"),
      h3("Step 4: Loot"),
      h3("Step 5: Repeat"),
      h2("Understanding Loot"),
      h3("Common Loot Types"),
      h3("Globals and Hall of Fame"),
      h3("Markup"),
      h2("Skills and Progression"),
      h3("Weapon Skills"),
      h3("Defense Skills"),
      h3("The Codex"),
      h3("SIB Weapons"),
      h2("Managing Costs"),
      h3("Cost Per Shot"),
      h3("DPP (Damage Per PEC)"),
      h3("Efficiency"),
      h2("Team Hunting"),
      h2("Survival Tips"),
      h2("Common Beginner Mistakes"),
    ],
  },
];

async function seed() {
  for (const guide of guides) {
    console.log(`Stripping ${guide.title}...`);
    await client.patch(guide.id).set({ body: guide.body }).commit();
    console.log(`  Done`);
  }
  console.log("\nAll guides stripped to skeleton headings.");
}

seed().catch((err) => { console.error("Failed:", err.message); process.exit(1); });
